// Generated by CoffeeScript 1.3.3

exports.attach = function() {
  this.helpers['jpg2'] = function(name) {
    return center(function() {
      return img({
        src: "http://" + name + ".jpg.to",
        style: 'max-height: 90%;max-width:90%'
      });
    });
  };
  this.helpers['slide'] = function(title, jpg, fn) {
    if (typeof jpg === 'function') {
      fn = jpg;
      jpg = null;
    }
    return section('.container.hero-unit', function() {
      if (title != null) {
        h1({
          style: 'margin-bottom: 20px;'
        }, title);
      }
      if (jpg != null) {
        jpg2(jpg);
      }
      if (fn != null) {
        return fn();
      }
    });
  };
  this.helpers['ruby'] = function(codeText) {
    return div('.row', function() {
      return div('.span6', function() {
        return pre('.prettyprint', function() {
          return code('.language-ruby', codeText);
        });
      });
    });
  };
  this.helpers['sql'] = function(codeText) {
    return div('.row', function() {
      return div('.span6', function() {
        return pre('.prettyprint', function() {
          return code('.language-sql', codeText);
        });
      });
    });
  };
  this.helpers['js'] = function(codeText) {
    return div('.row', function() {
      return div('.span6', function() {
        return pre('.prettyprint', function() {
          return code('.language-javascript', codeText);
        });
      });
    });
  };
  return this.helpers['escape'] = function(html) {
    return html.replace(/</g, '&lt;').replace(/>/, '&gt;');
  };
};
